# Generated by Django 4.0.9 on 2023-03-20 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
                ('date_of_death', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='graffiti.tag')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='graffiti.tag')),
            ],
        ),
        migrations.CreateModel(
            name='GraffitiWall',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('identifier', models.CharField(max_length=100, verbose_name='Identifier refers to the image filename.')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graffiti.house')),
                ('tags', models.ManyToManyField(to='graffiti.tag')),
            ],
        ),
        migrations.CreateModel(
            name='GraffitiPhoto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Name', max_length=100)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('identifier', models.CharField(max_length=100, verbose_name='Identifier refers to the image filename.')),
                ('canvas', models.TextField(default='0,0,0,0')),
                ('graffiti_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graffiti.graffitiwall')),
                ('related_graffiti', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_graffiti', to='graffiti.graffitiwall')),
            ],
        ),
        migrations.CreateModel(
            name='AncillarySource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('image', 'Image'), ('newsprint', 'Newsprint'), ('wall', 'Wall'), ('letter', 'Letter'), ('photograph', 'Photograph'), ('drawing', 'Drawing'), ('artwork', 'Artwork'), ('game', 'Game'), ('poem', 'Poem'), ('other', 'Other')], max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('contributor', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(max_length=100)),
                ('rights', models.CharField(max_length=100)),
                ('box', models.CharField(max_length=225, null=True)),
                ('folder', models.CharField(max_length=225, null=True)),
                ('access_rights', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('transcription', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graffiti.archive')),
                ('graffiti_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graffiti.graffitiwall')),
                ('grantee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grantee', to='graffiti.person')),
                ('grantor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grantor', to='graffiti.person')),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graffiti.house')),
                ('person', models.ManyToManyField(to='graffiti.person')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='graffiti.person')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='graffiti.person')),
                ('tags', models.ManyToManyField(to='graffiti.tag')),
            ],
        ),
    ]
