# Generated by Django 5.1.2 on 2024-10-22 13:34

import django.db.models.deletion
import prose.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GraffitiWall",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", prose.fields.RichTextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "room",
                    models.CharField(
                        help_text="Record the room name/number.", max_length=255
                    ),
                ),
                (
                    "spatial_position",
                    models.CharField(
                        help_text="Record the region code for this wall (e.g., B1, C3.",
                        max_length=100,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Identifier refers to the number produced by the camera/phone. Please ensure these match.",
                        max_length=100,
                    ),
                ),
                (
                    "date_taken",
                    models.DateField(
                        help_text="Record the date the photograph was taken."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("place", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="If left blank, the system will attempt to geocode the information if address and state information are provided.",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="If left blank, the system will attempt to geocode the information if address and state information are provided.",
                        max_digits=9,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["state", "city", "place"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, help_text="Enter the date as YYYY-MM-DD.", null=True
                    ),
                ),
                (
                    "date_of_death",
                    models.DateField(
                        blank=True, help_text="Enter the date as YYYY-MM-DD.", null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "People",
            },
        ),
        migrations.CreateModel(
            name="AncillarySource",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(null=True, upload_to="images/")),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("newsprint", "Newsprint"),
                            ("wall", "Wall"),
                            ("letter", "Letter"),
                            ("photograph", "Photograph"),
                            ("drawing", "Drawing"),
                            ("artwork", "Artwork"),
                            ("game", "Game"),
                            ("poem", "Poem"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        help_text="An entity primarily responsible for making the resource.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "contributor",
                    models.CharField(
                        blank=True,
                        help_text="An entity responsible for making contributions to the resource.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("date", models.CharField(blank=True, max_length=100, null=True)),
                ("language", models.CharField(blank=True, max_length=100, null=True)),
                ("box", models.CharField(blank=True, max_length=225, null=True)),
                ("folder", models.CharField(blank=True, max_length=225, null=True)),
                (
                    "access_rights",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("transcription", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "archive",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graffiti.archive",
                    ),
                ),
                (
                    "graffiti_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graffiti.graffitiwall",
                        verbose_name="Associated wall",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graffiti.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GraffitiPhoto",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="Name", max_length=100)),
                ("image", models.ImageField(null=True, upload_to="images/")),
                (
                    "identifier",
                    models.CharField(
                        help_text="Identifier refers to the number produced by the camera/phone. Please ensure these match.",
                        max_length=100,
                    ),
                ),
                ("canvas", models.TextField(blank=True, null=True)),
                (
                    "canvas_coords",
                    models.TextField(blank=True, default="[]", null=True),
                ),
                (
                    "graffiti_id",
                    models.ForeignKey(
                        help_text="Select the graffiti wall this photo belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graffiti.graffitiwall",
                        verbose_name="Graffiti wall",
                    ),
                ),
                (
                    "related_graffiti",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_graffiti",
                        to="graffiti.graffitiwall",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="archive",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="graffiti.location"
            ),
        ),
        migrations.CreateModel(
            name="DocumentPersonRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SENDER", "Sender"),
                            ("RECIPIENT", "Recipient"),
                            ("GRANTEE", "Grantee"),
                            ("GRANTOR", "Grantor"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graffiti.ancillarysource",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graffiti.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "People",
                "verbose_name_plural": "People",
            },
        ),
        migrations.AddField(
            model_name="ancillarysource",
            name="people",
            field=models.ManyToManyField(
                through="graffiti.DocumentPersonRole", to="graffiti.person"
            ),
        ),
        migrations.CreateModel(
            name="Alias",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "alias_type",
                    models.CharField(
                        choices=[("ALIAS", "Alias"), ("WALL", "Wall name")],
                        max_length=5,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graffiti.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alias",
                "verbose_name_plural": "Aliases",
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graffiti.location",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="graffitiwall",
            name="site_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="graffiti.site",
                verbose_name="Site",
            ),
        ),
        migrations.AddField(
            model_name="ancillarysource",
            name="site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="graffiti.site",
            ),
        ),
        migrations.CreateModel(
            name="WallRecordHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=10)),
                ("data", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "photo_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="graffiti.graffitiwall",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Wall Record Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="documentpersonrole",
            index=models.Index(
                fields=["person", "document", "role"],
                name="graffiti_do_person__da20c1_idx",
            ),
        ),
    ]
