# Generated by Django 5.1.2 on 2024-10-28 19:26

import taggit_selectize.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ancillarysource",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="graffitiwall",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="ancillarysource",
            name="date",
            field=models.CharField(
                blank=True,
                help_text="The date of the source, if known.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="graffitiwall",
            name="spatial_position",
            field=models.CharField(
                help_text="Record the region code for this wall (e.g., B1, C3).",
                max_length=100,
            ),
        ),
    ]
