# Generated by Django 5.1.2 on 2024-11-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="graffitiphoto",
            name="canvas",
        ),
        migrations.RemoveField(
            model_name="graffitiphoto",
            name="canvas_coords",
        ),
        migrations.AlterField(
            model_name="graffitiphoto",
            name="coordinates",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
