# Generated by Django 4.0.9 on 2023-03-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graffiti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ancillarysource',
            name='rights',
        ),
        migrations.RemoveField(
            model_name='ancillarysource',
            name='subject',
        ),
    ]
