# Generated by Django 4.0.9 on 2023-02-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graffiti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graffitihaspart',
            name='canvas',
            field=models.TextField(default='0,0,0,0'),
        ),
        migrations.AddField(
            model_name='graffitihaspart',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
