# Generated by Django 4.1.7 on 2024-10-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graffitiphoto",
            name="identifier",
            field=models.CharField(
                help_text="Identifier refers to the number produced by the camera/phone. Please ensure these match.",
                max_length=100,
            ),
        ),
    ]
