# Generated by Django 4.1.7 on 2024-10-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0002_alter_graffitiphoto_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="If left blank, the system will attempt to geocode the information if address and state information are provided.",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="If left blank, the system will attempt to geocode the information if address and state information are provided.",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="date_of_death",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
