# Generated by Django 4.1.7 on 2023-03-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graffiti', '0002_remove_ancillarysource_rights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancillarysource',
            name='access_rights',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ancillarysource',
            name='box',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='ancillarysource',
            name='creator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ancillarysource',
            name='folder',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='ancillarysource',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ancillarysource',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ancillarysource',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ancillarysource',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ancillarysource',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graffitiwall',
            name='identifier',
            field=models.CharField(help_text='Identifier refers to the image filename.', max_length=100),
        ),
    ]
