# Generated by Django 4.0.9 on 2023-02-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graffiti', '0002_graffitihaspart_canvas_graffitihaspart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='graffitihaspart',
            name='name',
            field=models.CharField(default='Name', max_length=100),
        ),
    ]
