# Generated by Django 5.1.2 on 2024-10-28 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "graffiti",
            "0002_ancillarysource_tags_graffitiwall_tags_person_tags_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="first_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="person",
            name="last_name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="person",
            name="middle_name_or_initial",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="place",
            field=models.CharField(max_length=255, verbose_name="Display name"),
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "person",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graffiti.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("military_rank", models.CharField(blank=True, max_length=255)),
                ("military_unit", models.CharField(blank=True, max_length=255)),
                ("military_branch", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graffiti.person",
                    ),
                ),
            ],
        ),
    ]
