# Generated by Django 5.1.2 on 2024-12-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0002_remove_graffitiphoto_canvas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graffitiwall",
            name="spatial_position",
            field=models.CharField(
                help_text="Mike's record the region code for this wall (e.g., B1, C3).",
                max_length=100,
            ),
        ),
    ]
