# Generated by Django 4.1.7 on 2024-10-16 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0003_alter_location_address_alter_location_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="date",
        ),
        migrations.AlterField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(
                blank=True, help_text="Enter the date as YYYY-MM-DD.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="date_of_death",
            field=models.DateField(
                blank=True, help_text="Enter the date as YYYY-MM-DD.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="site",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="graffiti.location",
            ),
        ),
    ]
