# Generated by Django 5.1.2 on 2024-10-31 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0003_person_first_name_person_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alias",
            name="alias_type",
        ),
    ]
