# Generated by Django 5.1.2 on 2024-12-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0003_alter_graffitiwall_spatial_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="graffitiwall",
            name="has_part",
        ),
        migrations.AddField(
            model_name="graffitiwall",
            name="interpretation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="graffitiwall",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="graffitiwall",
            name="wall_grid_position",
            field=models.CharField(
                default="",
                help_text="General record the wall grid position. For example, A1 or A1A2. Please consult the grid image reference for more information.",
                max_length=100,
            ),
        ),
    ]
