# Generated by Django 4.0.9 on 2023-02-27 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graffiti', '0003_graffitihaspart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='graffiti',
            name='tags',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='graffitihaspart',
            name='related_graffiti',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_graffiti', to='graffiti.graffiti'),
        ),
    ]
