# Generated by Django 4.0.9 on 2023-03-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graffiti', '0004_graffiti_tags_graffitihaspart_related_graffiti'),
    ]

    operations = [
        migrations.CreateModel(
            name='AncillarySource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='sources/')),
                ('access_rights', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
                ('date_of_death', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='graffiti',
            name='tags',
        ),
        migrations.CreateModel(
            name='MetadataForServiceRecords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('transcription', models.TextField()),
                ('ancillary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graffiti.ancillarysource')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graffiti.person')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataForMaps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('transcription', models.TextField()),
                ('ancillary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graffiti.ancillarysource')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataForLetters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('transcription', models.TextField()),
                ('ancillary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graffiti.ancillarysource')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='graffiti.person')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graffiti.person')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataForDeeds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('grantor', models.CharField(max_length=100)),
                ('grantee', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('transcription', models.TextField()),
                ('ancillary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graffiti.ancillarysource')),
            ],
        ),
        migrations.AddField(
            model_name='ancillarysource',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graffiti.archive'),
        ),
        migrations.AddField(
            model_name='ancillarysource',
            name='graffiti_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graffiti.graffiti'),
        ),
        migrations.AddField(
            model_name='ancillarysource',
            name='tags',
            field=models.ManyToManyField(to='graffiti.tag'),
        ),
        migrations.AddField(
            model_name='graffiti',
            name='tags',
            field=models.ManyToManyField(to='graffiti.tag'),
        ),
    ]
