# Generated by Django 5.1.2 on 2024-12-12 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0004_remove_graffitiwall_has_part_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="associated_graffiti_photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graffiti_associated_person",
                to="graffiti.graffitiphoto",
                verbose_name="Associated photo",
            ),
        ),
        migrations.AlterField(
            model_name="graffitiwall",
            name="wall_grid_position",
            field=models.CharField(
                help_text="General record the wall grid position. For example, A1 or A1A2. Please consult the grid image reference for more information.",
                max_length=100,
            ),
        ),
    ]
