# Generated by Django 4.1.7 on 2023-03-29 20:06

import prose.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0004_articlecontent_alter_graffitiwall_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graffitiwall",
            name="description",
            field=prose.fields.RichTextField(),
        ),
        migrations.DeleteModel(
            name="ArticleContent",
        ),
    ]
