# Generated by Django 5.1.2 on 2024-10-31 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0004_remove_alias_alias_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="name",
        ),
    ]
