# Generated by Django 5.1.2 on 2024-12-12 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0005_person_associated_graffiti_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="graffitiphoto",
            name="has_part",
        ),
    ]
