# Generated by Django 4.0.9 on 2023-03-10 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graffiti', '0005_ancillarysource_archive_person_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatafordeeds',
            name='grantee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grantee', to='graffiti.person'),
        ),
        migrations.AlterField(
            model_name='metadatafordeeds',
            name='grantor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graffiti.person'),
        ),
        migrations.CreateModel(
            name='MetadataForOther',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('transcription', models.TextField()),
                ('ancillary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graffiti.ancillarysource')),
                ('people', models.ManyToManyField(to='graffiti.person')),
            ],
        ),
    ]
