# Generated by Django 4.1.7 on 2024-10-16 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0005_alias_alter_ancillarysource_contributor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alias",
            name="person",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="graffiti.person",
            ),
        ),
    ]
