# Generated by Django 5.1.2 on 2024-10-31 18:19

import django.utils.timezone
import prose.fields
import taggit_selectize.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0005_remove_person_name"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="graffitiphoto",
            name="name",
        ),
        migrations.AddField(
            model_name="graffitiphoto",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="graffitiphoto",
            name="description",
            field=prose.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="graffitiphoto",
            name="graffiti_type",
            field=models.CharField(
                choices=[
                    ("Item 1", "Item 1"),
                    ("Item 2", "Item 2"),
                    ("Item 3", "Item 3"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="graffitiphoto",
            name="has_part",
            field=models.ManyToManyField(
                blank=True,
                help_text="A related resource that is included either physically or logically in the described resource.",
                related_name="graffiti_has_part",
                to="graffiti.graffitiwall",
            ),
        ),
        migrations.AddField(
            model_name="graffitiphoto",
            name="is_part_of",
            field=models.ManyToManyField(
                blank=True,
                help_text="A related resource in which the described resource is physically or logically included.",
                related_name="graffiti_is_part_of",
                to="graffiti.graffitiwall",
            ),
        ),
        migrations.AddField(
            model_name="graffitiphoto",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="graffitiphoto",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="graffitiwall",
            name="has_part",
            field=models.ManyToManyField(
                blank=True,
                help_text="A related resource that is included either physically or logically in the described resource.",
                related_name="graffiti_photo_has_part",
                to="graffiti.graffitiphoto",
            ),
        ),
    ]
