# Generated by Django 4.1.7 on 2023-04-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0005_alter_graffitiwall_description_delete_articlecontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="graffitiphoto",
            name="canvas_coords",
            field=models.TextField(blank=True, default="[]", null=True),
        ),
        migrations.AlterField(
            model_name="graffitiphoto",
            name="canvas",
            field=models.TextField(blank=True, null=True),
        ),
    ]
