# Generated by Django 4.1.7 on 2023-05-10 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0006_graffitiphoto_canvas_coords_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ancillarysource",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="graffitiwall",
            name="house_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="graffiti.house",
                verbose_name="House",
            ),
        ),
        migrations.AlterField(
            model_name="graffitiwall",
            name="identifier",
            field=models.CharField(
                help_text="Identifier refers to the image filename. Please ensure these match.",
                max_length=100,
            ),
        ),
    ]
