# Generated by Django 5.1.2 on 2024-10-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "graffiti",
            "0006_remove_graffitiphoto_name_graffitiphoto_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="graffitiphoto",
            name="coordinates",
            field=models.JSONField(null=True),
        ),
    ]
