# Generated by Django 4.0.9 on 2023-03-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graffiti', '0006_alter_metadatafordeeds_grantee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='box',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='archive',
            name='folder',
            field=models.CharField(default='', max_length=255),
        ),
    ]
