# Generated by Django 5.1.2 on 2024-12-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0006_remove_graffitiphoto_has_part"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graffitiphoto",
            name="graffiti_type",
            field=models.CharField(
                choices=[
                    ("name", "name"),
                    ("image", "image"),
                    ("unit", "unit"),
                    ("other", "other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="graffitiwall",
            name="wall_grid_position",
            field=models.CharField(
                help_text="General record for the wall grid position. For example, A1 or A1A2. Please consult the grid image reference for more information.",
                max_length=100,
            ),
        ),
    ]
