# Generated by Django 5.1.2 on 2025-01-24 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0007_alter_graffitiphoto_graffiti_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ancillarysource",
            name="archive",
        ),
        migrations.RemoveField(
            model_name="ancillarysource",
            name="graffiti_id",
        ),
        migrations.RemoveField(
            model_name="ancillarysource",
            name="location",
        ),
        migrations.RemoveField(
            model_name="ancillarysource",
            name="people",
        ),
        migrations.RemoveField(
            model_name="ancillarysource",
            name="site",
        ),
        migrations.RemoveField(
            model_name="ancillarysource",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="documentpersonrole",
            name="document",
        ),
        migrations.RemoveField(
            model_name="archive",
            name="location",
        ),
        migrations.RemoveField(
            model_name="documentpersonrole",
            name="person",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="person",
        ),
        migrations.RemoveField(
            model_name="person",
            name="associated_graffiti_photo",
        ),
        migrations.RemoveField(
            model_name="person",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="service",
            name="person",
        ),
        migrations.DeleteModel(
            name="Alias",
        ),
        migrations.DeleteModel(
            name="AncillarySource",
        ),
        migrations.DeleteModel(
            name="Archive",
        ),
        migrations.DeleteModel(
            name="DocumentPersonRole",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
    ]
