# Generated by Django 4.1.7 on 2023-05-11 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0007_ancillarysource_image_alter_graffitiwall_house_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ancillarysource",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="graffitiwall",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="house",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="person",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
