# Generated by Django 5.1.2 on 2025-01-27 15:10

import django.db.models.deletion
import prose.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0008_remove_ancillarysource_archive_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalGraffitiPhoto",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                (
                    "graffiti_type",
                    models.CharField(
                        choices=[
                            ("name", "name"),
                            ("image", "image"),
                            ("unit", "unit"),
                            ("other", "other"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("description", prose.fields.RichTextField(blank=True, null=True)),
                ("image", models.TextField(max_length=100, null=True)),
                (
                    "identifier",
                    models.CharField(
                        help_text="Identifier refers to the number produced by the camera/phone. Please ensure these match.",
                        max_length=100,
                    ),
                ),
                ("coordinates", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "graffiti_wall",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Select the graffiti wall this photo belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="graffiti.graffitiwall",
                        verbose_name="Graffiti wall",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical graffiti photo",
                "verbose_name_plural": "historical graffiti photos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalGraffitiWall",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                ("name", models.CharField(max_length=100)),
                ("description", prose.fields.RichTextField(blank=True, null=True)),
                ("image", models.TextField(max_length=100)),
                (
                    "room",
                    models.CharField(
                        help_text="Record the room name/number.", max_length=255
                    ),
                ),
                (
                    "spatial_position",
                    models.CharField(
                        help_text="Mike's record the region code for this wall (e.g., B1, C3).",
                        max_length=100,
                    ),
                ),
                (
                    "wall_grid_position",
                    models.CharField(
                        help_text="General record for the wall grid position. For example, A1 or A1A2. Please consult the grid image reference for more information.",
                        max_length=100,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Identifier refers to the number produced by the camera/phone. Please ensure these match.",
                        max_length=100,
                    ),
                ),
                (
                    "date_taken",
                    models.DateField(
                        help_text="Record the date the photograph was taken."
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("interpretation", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site_id",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="graffiti.site",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical graffiti wall",
                "verbose_name_plural": "historical graffiti walls",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLocation",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                (
                    "place",
                    models.CharField(max_length=255, verbose_name="Display name"),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="If left blank, the system will attempt to geocode the information if address and state information are provided.",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="If left blank, the system will attempt to geocode the information if address and state information are provided.",
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Location",
                "verbose_name_plural": "historical Locations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSite",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.TextField(blank=True, max_length=100, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="graffiti.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical site",
                "verbose_name_plural": "historical sites",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name="WallRecordHistory",
        ),
    ]
