# Generated by Django 4.0.9 on 2023-03-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graffiti', '0008_remove_graffitihaspart_part_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetadataForDeeds',
            new_name='MetadataForDeed',
        ),
        migrations.RenameModel(
            old_name='MetadataForLetters',
            new_name='MetadataForLetter',
        ),
        migrations.RenameModel(
            old_name='MetadataForMaps',
            new_name='MetadataForMap',
        ),
        migrations.RenameModel(
            old_name='MetadataForServiceRecords',
            new_name='MetadataForServiceRecord',
        ),
    ]
