# Generated by Django 5.1.2 on 2024-10-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0008_remove_graffitiphoto_related_graffiti"),
    ]

    operations = [
        migrations.RenameField(
            model_name="graffitiphoto",
            old_name="graffiti_id",
            new_name="graffiti_wall",
        ),
        migrations.AlterField(
            model_name="graffitiphoto",
            name="image",
            field=models.ImageField(null=True, upload_to="images/derived/"),
        ),
    ]
