# Generated by Django 4.0.9 on 2023-03-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graffiti', '0009_rename_metadatafordeeds_metadatafordeed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ancillarysource',
            name='image',
        ),
    ]
