# Generated by Django 4.1.7 on 2023-06-26 16:24

import taggit_selectize.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("graffiti", "0009_ancillarysource_tags_graffitiwall_tags_house_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ancillarysource",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="graffitiwall",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="date",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="house",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
