# Generated by Django 5.1.2 on 2025-01-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0009_historicalgraffitiphoto_historicalgraffitiwall_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graffitiphoto",
            name="identifier",
            field=models.CharField(
                help_text="An auto-generated unique identifier for the photo.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgraffitiphoto",
            name="identifier",
            field=models.CharField(
                help_text="An auto-generated unique identifier for the photo.",
                max_length=100,
            ),
        ),
    ]
