# Generated by Django 5.1.2 on 2025-02-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0010_alter_graffitiphoto_identifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="graffitiwall",
            name="archival_image",
            field=models.ImageField(
                blank=True,
                help_text="An archival quality image. Optional.",
                null=True,
                upload_to="images/archival/",
            ),
        ),
        migrations.AddField(
            model_name="graffitiwall",
            name="conservation_notes",
            field=models.TextField(
                blank=True, help_text="Conservation notes.", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalgraffitiwall",
            name="archival_image",
            field=models.TextField(
                blank=True,
                help_text="An archival quality image. Optional.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalgraffitiwall",
            name="conservation_notes",
            field=models.TextField(
                blank=True, help_text="Conservation notes.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="graffitiwall",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Internal project notes.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalgraffitiwall",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Internal project notes.", null=True
            ),
        ),
    ]
