# Generated by Django 5.1.2 on 2025-02-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0011_graffitiwall_archival_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graffitiphoto",
            name="graffiti_type",
            field=models.CharField(
                choices=[
                    ("drawing", "drawing"),
                    ("image", "image"),
                    ("name", "name"),
                    ("poetry", "poetry"),
                    ("unit", "unit"),
                    ("other writing", "other writing"),
                    ("other", "other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgraffitiphoto",
            name="graffiti_type",
            field=models.CharField(
                choices=[
                    ("drawing", "drawing"),
                    ("image", "image"),
                    ("name", "name"),
                    ("poetry", "poetry"),
                    ("unit", "unit"),
                    ("other writing", "other writing"),
                    ("other", "other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
