# Generated by Django 6.1 on 2026-09-14 16:17

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def copy_rectangles(apps, schema_editor):
    GraffitiPhoto = apps.get_model("graffiti", "GraffitiPhoto")
    for photo in GraffitiPhoto.objects.exclude(coordinates=None):
        canvas = (photo.coordinates or {}).get("canvas") or {}
        if all(key in canvas for key in ("x", "y", "width", "height")):
            photo.x, photo.y = canvas["x"], canvas["y"]
            photo.width, photo.height = canvas["width"], canvas["height"]
            photo.save(update_fields=["x", "y", "width", "height"])



class Migration(migrations.Migration):

    dependencies = [
        ('graffiti', '0012_alter_graffitiphoto_graffiti_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graffitiphoto',
            name='is_part_of',
        ),
        migrations.AddField(
            model_name='graffitiphoto',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graffitiphoto',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graffitiphoto',
            name='x',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graffitiphoto',
            name='y',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgraffitiphoto',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgraffitiphoto',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgraffitiphoto',
            name='x',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgraffitiphoto',
            name='y',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graffitiphoto',
            name='coordinates',
            field=models.JSONField(blank=True, help_text='Raw metadata captured by the crop tool.', null=True),
        ),
        migrations.AlterField(
            model_name='graffitiphoto',
            name='identifier',
            field=models.CharField(help_text='An auto-generated unique identifier for the photo.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalgraffitiphoto',
            name='coordinates',
            field=models.JSONField(blank=True, help_text='Raw metadata captured by the crop tool.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalgraffitiphoto',
            name='identifier',
            field=models.CharField(db_index=True, help_text='An auto-generated unique identifier for the photo.', max_length=100),
        ),
        migrations.CreateModel(
            name='HistoricalMultispectralImage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('image', models.TextField(max_length=100)),
                ('band', models.CharField(help_text="Wavelength or band captured, e.g. 'IR 850nm' or 'UV'.", max_length=100)),
                ('captured_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('graffiti_wall', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='graffiti.graffitiwall')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical multispectral image',
                'verbose_name_plural': 'historical multispectral images',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MultispectralImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/multispectral/')),
                ('band', models.CharField(help_text="Wavelength or band captured, e.g. 'IR 850nm' or 'UV'.", max_length=100)),
                ('captured_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graffiti_wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multispectral_images', to='graffiti.graffitiwall')),
            ],
        ),
        migrations.RunPython(copy_rectangles, migrations.RunPython.noop),
    ]
