# Generated by Django 6.1 on 2026-09-29 15:34

from django.db import migrations, models


def drawing_to_image(apps, schema_editor):
    GraffitiPhoto = apps.get_model("graffiti", "GraffitiPhoto")
    GraffitiPhoto.objects.filter(graffiti_type="drawing").update(graffiti_type="image")


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0014_created_by"),
    ]

    operations = [
        migrations.RunPython(drawing_to_image, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="graffitiphoto",
            name="graffiti_type",
            field=models.CharField(
                choices=[
                    ("image", "image"),
                    ("name", "name"),
                    ("poetry", "poetry"),
                    ("unit", "unit"),
                    ("other writing", "other writing"),
                    ("other", "other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgraffitiphoto",
            name="graffiti_type",
            field=models.CharField(
                choices=[
                    ("image", "image"),
                    ("name", "name"),
                    ("poetry", "poetry"),
                    ("unit", "unit"),
                    ("other writing", "other writing"),
                    ("other", "other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
