# Generated by Django 6.1 on 2026-09-29 19:40

import logging

from django.db import migrations, models

logger = logging.getLogger(__name__)


def store_image_dimensions(apps, schema_editor):
    """Record each wall image's size, skipping files that can't be read."""
    GraffitiWall = apps.get_model("graffiti", "GraffitiWall")
    skipped = 0
    for wall in GraffitiWall.objects.exclude(image="").only("id", "image"):
        try:
            width, height = wall.image.width, wall.image.height
        except (OSError, ValueError):
            width = height = None
        if not (width and height):
            skipped += 1
            continue
        # update() rather than save(): no edit-history entry for a backfill.
        GraffitiWall.objects.filter(pk=wall.pk).update(
            image_width=width, image_height=height
        )
    if skipped:
        logger.warning(
            "Stored no image size for %s wall(s) whose image file could not be read",
            skipped,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0016_graffitiphoto_description_to_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="graffitiwall",
            name="image_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="graffitiwall",
            name="image_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="historicalgraffitiwall",
            name="image_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="historicalgraffitiwall",
            name="image_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(store_image_dimensions, migrations.RunPython.noop),
    ]
