---
version: 2
updates:
  - package-ecosystem: "pip"
    versioning-strategy: "increase"
    directories:
      - "/"
    groups:
      all-django-dependencies:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
    target-branch: "main"
    reviewers:
      - "chnm/systems"
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/theme/static_src"
    groups:
      all-npm-dependencies:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
    target-branch: "main"
    reviewers:
      - "chnm/systems"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "chnm/systems"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "chnm/systems"
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "chnm/systems"
