# Generated by Django 6.1 on 2026-09-29 19:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Senior Developer and Scholar",
                        max_length=255,
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("team", "Project team"),
                            ("collaborator", "Collaborators"),
                        ],
                        default="team",
                        max_length=20,
                    ),
                ),
                (
                    "affiliation",
                    models.CharField(
                        blank=True,
                        help_text="e.g. George Mason University",
                        max_length=255,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="A sentence or two, plain text."
                    ),
                ),
                ("photo", models.ImageField(blank=True, upload_to="team/")),
                ("website", models.URLField(blank=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Lower numbers are listed first within a group.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this person from the public Team page.",
                        verbose_name="Active",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Team member",
                "verbose_name_plural": "Team members",
                "ordering": ["group", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalTeamMember",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Senior Developer and Scholar",
                        max_length=255,
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("team", "Project team"),
                            ("collaborator", "Collaborators"),
                        ],
                        default="team",
                        max_length=20,
                    ),
                ),
                (
                    "affiliation",
                    models.CharField(
                        blank=True,
                        help_text="e.g. George Mason University",
                        max_length=255,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="A sentence or two, plain text."
                    ),
                ),
                ("photo", models.TextField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Lower numbers are listed first within a group.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this person from the public Team page.",
                        verbose_name="Active",
                    ),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Team member",
                "verbose_name_plural": "historical Team members",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
