# Generated by Django 6.1 on 2026-09-14 15:58

from django.db import migrations, models


def copy_photo_links(apps, schema_editor):
    Person = apps.get_model("people", "Person")
    for person in Person.objects.exclude(associated_graffiti_photo=None):
        person.associated_graffiti_photos.add(person.associated_graffiti_photo_id)


def restore_photo_links(apps, schema_editor):
    Person = apps.get_model("people", "Person")
    for person in Person.objects.all():
        first = person.associated_graffiti_photos.order_by("id").first()
        if first:
            person.associated_graffiti_photo = first
            person.save(update_fields=["associated_graffiti_photo"])


class Migration(migrations.Migration):

    dependencies = [
        ("graffiti", "0012_alter_graffitiphoto_graffiti_type_and_more"),
        ("people", "0003_historicalservice_date_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="associated_graffiti_photos",
            field=models.ManyToManyField(
                blank=True,
                related_name="associated_people",
                to="graffiti.graffitiphoto",
                verbose_name="Associated photos",
            ),
        ),
        migrations.RunPython(copy_photo_links, restore_photo_links),
        migrations.RemoveField(
            model_name="historicalperson",
            name="associated_graffiti_photo",
        ),
        migrations.RemoveField(
            model_name="person",
            name="associated_graffiti_photo",
        ),
    ]
