# Generated by Django 6.1 on 2026-09-29 15:34

from django.db import migrations, models

RANKS = {
    "private": "private",
    "corporal": "corporal",
    "sergeant": "sergeant",
    "2nd lieutenant": "2nd_lieutenant",
    "1st lieutenant": "1st_lieutenant",
    "lieutenant": "lieutenant",
    "captain": "captain",
    "major": "major",
    "lieutenant colonel": "lieutenant_colonel",
    "colonel": "colonel",
    "brigadier general": "brigadier_general",
}


def forwards(apps, schema_editor):
    Service = apps.get_model("people", "Service")
    # Cavalry moves from a military branch to an army branch.
    Service.objects.filter(military_branch="cavalry").update(
        military_branch="army", military_division="cavalry"
    )
    # Free-text ranks become choice values; unrecognized ranks are left as-is
    # so nothing is lost, and the admin asks for a valid choice on next save.
    for service in Service.objects.exclude(military_rank=""):
        rank = RANKS.get(" ".join(service.military_rank.lower().split()))
        if rank and rank != service.military_rank:
            service.military_rank = rank
            service.save(update_fields=["military_rank"])


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0005_created_by"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="historicalservice",
            name="military_branch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("army", "Army"),
                    ("navy", "Navy"),
                    ("coastguard", "Coast Guard"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicalservice",
            name="military_division",
            field=models.CharField(
                blank=True,
                choices=[
                    ("infantry", "Infantry"),
                    ("cavalry", "Cavalry"),
                    ("artillery", "Artillery"),
                    ("engineers", "Engineers"),
                    ("signal_corps", "Signal Corps"),
                    ("band", "Band"),
                ],
                max_length=255,
                verbose_name="Army branch",
            ),
        ),
        migrations.AlterField(
            model_name="historicalservice",
            name="military_rank",
            field=models.CharField(
                blank=True,
                choices=[
                    ("private", "Private"),
                    ("corporal", "Corporal"),
                    ("sergeant", "Sergeant"),
                    ("2nd_lieutenant", "2nd Lieutenant"),
                    ("1st_lieutenant", "1st Lieutenant"),
                    ("lieutenant", "Lieutenant"),
                    ("captain", "Captain"),
                    ("major", "Major"),
                    ("lieutenant_colonel", "Lieutenant Colonel"),
                    ("colonel", "Colonel"),
                    ("brigadier_general", "Brigadier General"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="military_branch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("army", "Army"),
                    ("navy", "Navy"),
                    ("coastguard", "Coast Guard"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="military_division",
            field=models.CharField(
                blank=True,
                choices=[
                    ("infantry", "Infantry"),
                    ("cavalry", "Cavalry"),
                    ("artillery", "Artillery"),
                    ("engineers", "Engineers"),
                    ("signal_corps", "Signal Corps"),
                    ("band", "Band"),
                ],
                max_length=255,
                verbose_name="Army branch",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="military_rank",
            field=models.CharField(
                blank=True,
                choices=[
                    ("private", "Private"),
                    ("corporal", "Corporal"),
                    ("sergeant", "Sergeant"),
                    ("2nd_lieutenant", "2nd Lieutenant"),
                    ("1st_lieutenant", "1st Lieutenant"),
                    ("lieutenant", "Lieutenant"),
                    ("captain", "Captain"),
                    ("major", "Major"),
                    ("lieutenant_colonel", "Lieutenant Colonel"),
                    ("colonel", "Colonel"),
                    ("brigadier_general", "Brigadier General"),
                ],
                max_length=255,
            ),
        ),
    ]
