# Generated by Django 5.1.2 on 2025-01-27 15:10

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graffiti", "0009_historicalgraffitiphoto_historicalgraffitiwall_and_more"),
        ("people", "0002_historicalalias_historicalorganization_and_more"),
        ("source", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalAncillarySource",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                ("title", models.CharField(max_length=100)),
                ("image", models.TextField(max_length=100, null=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("newsprint", "Newsprint"),
                            ("wall", "Wall"),
                            ("letter", "Letter"),
                            ("photograph", "Photograph"),
                            ("drawing", "Drawing"),
                            ("artwork", "Artwork"),
                            ("game", "Game"),
                            ("poem", "Poem"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        help_text="An entity primarily responsible for making the resource.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "contributor",
                    models.CharField(
                        blank=True,
                        help_text="An entity responsible for making contributions to the resource.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        blank=True,
                        help_text="The date of the source, if known.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=100, null=True)),
                ("box", models.CharField(blank=True, max_length=225, null=True)),
                ("folder", models.CharField(blank=True, max_length=225, null=True)),
                (
                    "access_rights",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("transcription", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "archive",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="source.archive",
                    ),
                ),
                (
                    "graffiti_id",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="graffiti.graffitiwall",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="graffiti.location",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="graffiti.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ancillary source",
                "verbose_name_plural": "historical ancillary sources",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalArchive",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="graffiti.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical archive",
                "verbose_name_plural": "historical archives",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDocumentPersonRole",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SENDER", "Sender"),
                            ("RECIPIENT", "Recipient"),
                            ("GRANTEE", "Grantee"),
                            ("GRANTOR", "Grantor"),
                        ],
                        max_length=100,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="source.ancillarysource",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical People",
                "verbose_name_plural": "historical People",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
