# Generated by Django 5.1.2 on 2025-02-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source", "0002_historicalancillarysource_historicalarchive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ancillarysource",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("artwork", "Artwork"),
                    ("document", "Document"),
                    ("drawing", "Drawing"),
                    ("game", "Game"),
                    ("image", "Image"),
                    ("letter", "Letter"),
                    ("newsprint", "Newsprint"),
                    ("photograph", "Photograph"),
                    ("poem", "Poem"),
                    ("wall", "Wall"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="historicalancillarysource",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("artwork", "Artwork"),
                    ("document", "Document"),
                    ("drawing", "Drawing"),
                    ("game", "Game"),
                    ("image", "Image"),
                    ("letter", "Letter"),
                    ("newsprint", "Newsprint"),
                    ("photograph", "Photograph"),
                    ("poem", "Poem"),
                    ("wall", "Wall"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
