# Generated by Django 6.1 on 2026-09-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_alter_ancillarysource_item_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancillarysource',
            name='item_type',
            field=models.CharField(choices=[('artwork', 'Artwork'), ('document', 'Document'), ('drawing', 'Drawing'), ('game', 'Game'), ('image', 'Image'), ('letter', 'Letter'), ('newsprint', 'Newsprint'), ('pensionfile', 'Pension File'), ('photograph', 'Photograph'), ('poem', 'Poem'), ('servicerecord', 'Service Record'), ('wall', 'Wall'), ('widowpensionfile', "Widow's Pension File"), ('other', 'Other')], default='document', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalancillarysource',
            name='item_type',
            field=models.CharField(choices=[('artwork', 'Artwork'), ('document', 'Document'), ('drawing', 'Drawing'), ('game', 'Game'), ('image', 'Image'), ('letter', 'Letter'), ('newsprint', 'Newsprint'), ('pensionfile', 'Pension File'), ('photograph', 'Photograph'), ('poem', 'Poem'), ('servicerecord', 'Service Record'), ('wall', 'Wall'), ('widowpensionfile', "Widow's Pension File"), ('other', 'Other')], default='document', max_length=100),
        ),
    ]
